quarkus:
  hibernate-orm:
    database:
      generation: drop-and-create
  datasource:
    db-kind: postgresql
    jdbc:
      url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: 1111

mp:
  messaging:
    incoming:
      creation-event:
        connector: smallrye-kafka
        bootstrap:
          servers: localhost:29092
    outgoing:
      creation-notify:
        connector: smallrye-kafka
        topic: prices
        bootstrap:
          servers: localhost:29092